;======================================================================
; TIMVDU DRIVER - CONSTANTS
;======================================================================
;
TERMENABLE	.SET	TRUE	; INCLUDE TERMINAL PSEUDODEVICE DRIVER


TIMVDU_BASE	.EQU	$8000		; BASE PORT FOR TIM
;
	DEVECHO	"TIMVDU: IO="
	DEVECHO	TIMVDU_BASE
	DEVECHO	"\n"
;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE HEADER
;--------------------------------------------------------------------------------------------------
;
ORG_TIMVDU	.EQU	$
;
	.DW	SIZ_TIMVDU		; MODULE SIZE
	.DW	TIMVDU_INITPHASE		; ADR OF INIT PHASE HANDLER
;
TIMVDU_INITPHASE:
	; INIT PHASE HANDLER, A=PHASE
	CP	HB_PHASE_PREINIT	; PREINIT PHASE?
	JP	Z,TIMVDU_PREINIT		; DO PREINIT
	CP	HB_PHASE_INIT		; INIT PHASE?
	JP	Z,TIMVDU_INIT		; DO INIT
	RET				; DONE
;
; HARDWARE RESET PRIOR TO ROMWBW CONSOLE INITIALIZATION
;
TIMVDU_PREINIT:
;
	LD	IY,TIMVDU_IDAT		; POINTER TO INSTANCE DATA
	CALL TIMVDU_VDAINI

	XOR	A			; SIGNAL SUCCESS
	RET				; DONE
;
; POST CONSOLE INITIALIZATION
;
TIMVDU_INIT:
	LD	IY,TIMVDU_IDAT		; POINTER TO INSTANCE DATA
	CALL	NEWLINE			; FORMATTING
	PRTS("TIMVDU: IO=$")
	LD	HL,TIMVDU_BASE
	CALL	PRTHEXWORDHL

	; ADD OURSELVES TO VDA DISPATCH TABLE
	LD	BC,TIMVDU_FNTBL		; BC := FUNCTION TABLE ADDRESS
	LD	DE,TIMVDU_IDAT		; DE := TIMVDU INSTANCE DATA PTR
	CALL	VDA_ADDENT		; ADD ENTRY, A := UNIT ASSIGNED

	; INITIALIZE EMULATION
	LD	C,A			; C := ASSIGNED VIDEO DEVICE NUM
	LD	DE,TIMVDU_FNTBL		; DE := FUNCTION TABLE ADDRESS
	LD	HL,TIMVDU_IDAT		; HL := TIMVDU INSTANCE DATA PTR
	CALL	TERM_ATTACH		; DO IT

	XOR	A			; SIGNAL SUCCESS
	RET				; DONE


;
;======================================================================
; TIMVDU DRIVER - VIDEO DISPLAY ADAPTER (VDA) FUNCTIONS
;======================================================================
;
TIMVDU_FNTBL:
	.DW	TIMVDU_VDAINI
	.DW	TIMVDU_VDAQRY
	.DW	TIMVDU_VDARES
	.DW	TIMVDU_VDADEV
	.DW	TIMVDU_VDASCS
	.DW	TIMVDU_VDASCP
	.DW	TIMVDU_VDASAT
	.DW	TIMVDU_VDASCO
	.DW	TIMVDU_VDAWRC
	.DW	TIMVDU_VDAFIL
	.DW	TIMVDU_VDACPY
	.DW	TIMVDU_VDASCR
	.DW	TIMKBD_STAT
	.DW	TIMKBD_FLUSH
	.DW	TIMKBD_READ
	.DW	TIMVDU_VDARDC
#IF (($ - TIMVDU_FNTBL) != (VDA_FNCNT * 2))
	.ECHO   "*** INVALID VGA FUNCTION TABLE ***\n"
	!!!!!
#ENDIF

TIMVDU_VDAINI:
; Fill screen memory
    LD      BC,TIMVDU_BASE
Loop:
	XOR     A
	OUT     (C),A
	INC     BC
	BIT     7,B
	JR      NZ,Loop 

	XOR	A			; SIGNAL SUCCESS
	RET

TIMVDU_VDAQRY:
	LD	C,$00		; MODE ZERO IS ALL WE KNOW
	LD	A,24
	LD	D,A
	LD	A,80
	LD	E,A
	LD	HL,$0		; EXTRACTION OF CURRENT BITMAP DATA NOT SUPPORTED YET
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDARES:
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDADEV:
	LD	C,0		; C := ATTRIBUTES (UNDEFINED)
	LD	D,VDADEV_TIM	; D := DEVICE TYPE
	LD	E,0		; E := PHYSICAL UNIT IS ALWAYS ZERO
	LD	H,0		; H := 0, DRIVER HAS NO MODES
	LD	L,$80		; L := BASE I/O ADDRESS
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDASCS:
	SYSCHKERR(ERR_NOTIMPL)	; NOT IMPLEMENTED (YET)
	RET

TIMVDU_VDASCP:
	; UNREVERSE THE CURRENT CURSOR
;	CALL	REVERSE_CURSOR_POS
;	CALL	TIMVDU_XY		; SET CURSOR POSITION
	LD A,D
	LD (ROW_POSITION), A
	LD A,E
	LD (COLUMN_POSITION), A

;	; REVERSE VIDEO THE CHARACTER AT THE NEW CURSOR POSITION
;	CALL	REVERSE_CURSOR_POS
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDASAT:
	; INCOMING IS:  -----RUB (R=REVERSE, U=UNDERLINE, B=BLINK)
	;
	; JUST SAVE THE VALUE AND FALL THROUGH.  ONLY REVERSE IS
	; SUPPORTED WHICH IS IMPLEMENTED BELOW.
;	LD	A,E
;	LD	(TIMVDU_RUB),A	; SAVE IT
;	JR	TIMVDU_VDASCO1	; IMPLEMENT SETTING

TIMVDU_VDASCO:
;	; WE HANDLE ONLY PER-CHARACTER COLORS (D=0)
;	LD	A,D		; GET CHAR/SCREEN SCOPE
;	OR	A		; CHARACTER?
;	JR	NZ,TIMVDU_VDASCO2	; IF NOT, JUST RETURN
;	LD	A,E
;	LD	(TIMVDU_ATTR),A	; SAVE COLOR INFO
;TIMVDU_VDASCO1:
;	; CHECK FOR REVERSE VIDEO
;	LD	A,(TIMVDU_RUB)	; GET RUB SETTING
;	BIT	2,A		; REVERSE IS BIT 2
;	JR	Z,TIMVDU_VDASCO2	; DONE IF REVERSE VID NOT SET
;	; IMPLEMENT REVERSE VIDEO
;	LD	A,(TIMVDU_ATTR)	; GET ATTRIBUTE
;	RLCA			; SWAP FG/BG COLORS
;	RLCA
;	RLCA
;	RLCA
;	LD	(TIMVDU_ATTR),A	; SAVE NEW VALUE
;TIMVDU_VDASCO2:
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDAWRC:
;	CALL	REVERSE_CURSOR_POS
;	LD	A,E		; CHARACTER TO WRITE GOES IN A
;	CALL	TIMVDU_PUTCHAR	; PUT IT ON THE SCREEN
;	CALL	REVERSE_CURSOR_POS
	LD	C,E		; CHARACTER TO WRITE GOES IN A
	CALL PRINT_CHAR
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDAFIL:
;	CALL	REVERSE_CURSOR_POS
;	LD	A,E		; FILL CHARACTER GOES IN A
;	LD	B,H
;	LD	C,L		; FILL LENGTH GOES IN BC
;	CALL	TIMVDU_FILL	; DO THE FILL
;	CALL	REVERSE_CURSOR_POS
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDACPY:
;	; LENGTH IN HL, SOURCE ROW/COL IN DE, DEST IS TIMVDU_POS
;	; BLKCPY USES: HL=SOURCE, DE=DEST, BC=COUNT
;	CALL	REVERSE_CURSOR_POS
;	PUSH	HL		; SAVE LENGTH
;	CALL	TIMVDU_XY2IDX	; ROW/COL IN DE -> SOURCE ADR IN HL
;	PUSH	DE
;	LD	DE,(TIMVDU_OFF)	; ADD IN VRAM START OFFSET
;	ADD	HL,DE
;	POP	DE
;	POP	BC		; RECOVER LENGTH IN BC
;	LD	DE,(TIMVDU_POS)	; PUT DEST IN DE
;;	LD	A,0		; SOURCE IS MEMORY
;	CALL	TIMVDU_BLKCPY	; DO A BLOCK COPY
;	CALL	REVERSE_CURSOR_POS
	XOR	A		; SIGNAL SUCCESS
	RET

TIMVDU_VDASCR:
	LD	A,E
	CALL	SCROLL_ONE_LINE
;	OR	A		; SET FLAGS
;	RET	Z		; IF ZERO, WE ARE DONE
;	JP	M,TIMVDU_VDASCR1	; E IS NEGATIVE, REVERSE SCROLL
;	CALL	TIMVDU_RSCROLL	; SCROLL FORWARD 'E' LINES
;	XOR	A		; SIGNAL SUCCESS
;	RET
;TIMVDU_VDASCR1:
;	NEG			; A IS NEGATIVE, BUT NEED IT POSITIVE
;	LD	E,A		; LINES TO SCROLL TO E
;	CALL	TIMVDU_SCROLL	; SCROLL REVERSE 'E' LINES
	XOR	A		; SIGNAL SUCCESS
	RET

TIMKBD_STAT:
TIMKBD_FLUSH:
TIMKBD_READ:
	OR	$FF		; RETURN FAILURE STATUS
	RET

TIMVDU_VDARDC:
	OR	$FF			; UNSUPPORTED FUNCTION
	RET


;
;
;
;
;

; **********************************************************************
; **  Terminal emulation
; **********************************************************************
SCROLL .EQU	$D0			; scroll register
;
; Prints one character
;
PRINT_CHAR:
	LD	B,10				;char is 10 pixels
	MLT BC				;char * 10 (pixela)
	LD	HL,CHARSET
	ADD	HL,BC				;BC is offset from start of font data
	EX	DE,HL
	CALL	GET_ADDRESS			;get RAM location in BC
	LD	L,10
	JR	C,PRINT_FROM_HALF		;if carry is set, char starts from half byte in screen RAM
PRINT_FROM_FULL:
	PUSH	HL
	LD	A,(DE)				;DE is character address in charset
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0FH
	LD	HL,PIXEL_TABLE
	ADD	A,L
	LD	L,A
	LD	A,(HL)
	OUT	(C),A
	INC	B
	LD	A,(DE)
	AND	0FH
	LD	HL,PIXEL_TABLE
	ADD	A,L
	LD	L,A
	LD	A,(HL)
	AND	0FH
	LD	L,A
	IN	A,(C)
	AND	0F0H
	OR	L
	OUT	(C),A
	DEC	B
	INC	C
	INC	DE
	POP	HL
	DEC	L
	JR	NZ,PRINT_FROM_FULL
	JR	PRINT_DONE
PRINT_FROM_HALF:
	PUSH	HL
	LD	A,(DE)
	RLCA
	RLCA
	AND	3
	LD	HL,PIXEL_TABLE
	ADD	A,L
	LD	L,A
	LD	A,(HL)
	AND	0F0H
	LD	L,A
	IN	A,(C)
	AND	0FH
	OR	L
	OUT	(C),A
	INC	B
	LD	A,(DE)
	RRCA
	RRCA
	AND	0FH
	LD	HL,PIXEL_TABLE
	ADD	A,L
	LD	L,A
	LD	A,(HL)
	OUT	(C),A
	DEC	B
	INC	C
	INC	DE
	POP	HL
	DEC	L
	JR	NZ,PRINT_FROM_HALF
PRINT_DONE:
	LD	A,(COLUMN_POSITION)
	INC	A
	CP	80				;end of row?
	JR	NZ,NEXT_COL			;no
	XOR	A				;yes, new column is zero
NEXT_COL:
	LD	(COLUMN_POSITION),A		;save new column position
	RET					;and finish

GET_ADDRESS:
	LD	A,(ROW_POSITION)
	LD	B,A
	LD	C,10
	MLT BC				;row x10
	LD	A,(SCROLL_LOCATION)
	ADD	A,C
	LD	C,A
	LD	A,(COLUMN_POSITION)
	LD	B,A
	ADD	A,A
	ADD	A,B				;col x3
	ADD	A,2				;+2
	SRL	A				;div /2
	LD	B,A
	SET	7,B				;plus high bit
	RET					;if carry set, it is odd char in row
	
SCROLL_ONE_LINE:
	LD	A,(SCROLL_LOCATION)
	ADD	A,10
	LD	(SCROLL_LOCATION),A
	OUT0	(SCROLL),A
	ADD	A,0E6H
	LD	C,A
	LD	B,080H
	LD	E,0DH

CLEAR_LINES_IN_E:
	XOR	A
CLRL1:	
	LD	D,E
	PUSH	BC
CLRL2:	
	OUT	(C),A
	INC	C
	OUT	(C),A
	INC	C
	DEC	D
	JR	NZ,CLRL2
	POP	BC
	INC	B
	JR	NZ,CLRL1
	RET
	
PIXEL_TABLE:

	.DB	$00
	.DB	$C0
	.DB	$30
	.DB	$F0
	.DB	$0C
	.DB	$CC
	.DB	$3C
	.DB	$FC
	.DB	$03
	.DB	$C3
	.DB	$33
	.DB	$F3
	.DB	$0F
	.DB	$CF
	.DB	$3F
	.DB	$FF

COLUMN_POSITION: .DB 0
ROW_POSITION:    .DB 0
SCROLL_LOCATION: .DB 0

#INCLUDE "timchar.asm"

;
;==================================================================================================
;   TIMVDU DRIVER - INSTANCE DATA
;==================================================================================================
;
TIMVDU_IDAT:
	.DB	KBDMODE_NONE
	.DB	0
	.DB	0

;
;--------------------------------------------------------------------------------------------------
;   HBIOS MODULE TRAILER
;--------------------------------------------------------------------------------------------------
;
END_TIMVDU	.EQU	$
SIZ_TIMVDU	.EQU	END_TIMVDU - ORG_TIMVDU
;	
	MEMECHO	"TIMVDU occupies "
	MEMECHO	SIZ_TIMVDU
	MEMECHO	" bytes.\n"
